# Generated by Django 2.0.3 on 2018-03-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20180320_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='billing_profie',
            new_name='billing_profile',
        ),
    ]
